# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x12infusion.telemetry\"A\n\x0cVitalReading\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"[\n\nPumpStatus\x12\x1b\n\x13rate_mcg_per_kg_min\x18\x01 \x01(\x01\x12\x17\n\x0f\x66\x61llback_active\x18\x02 \x01(\x08\x12\x17\n\x0f\x61larm_triggered\x18\x03 \x01(\x08\"\xb4\x02\n\x11TelemetryEnvelope\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x30\n\x06vitals\x18\x03 \x03(\x0b\x32 .infusion.telemetry.VitalReading\x12\x33\n\x0bpump_status\x18\x04 \x01(\x0b\x32\x1e.infusion.telemetry.PumpStatus\x12K\n\x0bpredictions\x18\x05 \x03(\x0b\x32\x36.infusion.telemetry.TelemetryEnvelope.PredictionsEntry\x12\x10\n\x08sequence\x18\x06 \x01(\x03\x1a\x32\n\x10PredictionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\" \n\x0cTelemetryAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32r\n\x12TelemetryIngestion\x12\\\n\x0fStreamTelemetry\x12%.infusion.telemetry.TelemetryEnvelope\x1a .infusion.telemetry.TelemetryAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYENVELOPE_PREDICTIONSENTRY']._loaded_options = None
  _globals['_TELEMETRYENVELOPE_PREDICTIONSENTRY']._serialized_options = b'8\001'
  _globals['_VITALREADING']._serialized_start=39
  _globals['_VITALREADING']._serialized_end=104
  _globals['_PUMPSTATUS']._serialized_start=106
  _globals['_PUMPSTATUS']._serialized_end=197
  _globals['_TELEMETRYENVELOPE']._serialized_start=200
  _globals['_TELEMETRYENVELOPE']._serialized_end=508
  _globals['_TELEMETRYENVELOPE_PREDICTIONSENTRY']._serialized_start=458
  _globals['_TELEMETRYENVELOPE_PREDICTIONSENTRY']._serialized_end=508
  _globals['_TELEMETRYACK']._serialized_start=510
  _globals['_TELEMETRYACK']._serialized_end=542
  _globals['_TELEMETRYINGESTION']._serialized_start=544
  _globals['_TELEMETRYINGESTION']._serialized_end=658
# @@protoc_insertion_point(module_scope)
